language: python
python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6
cache: pip
install: 
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
before_script:
    - flake8 .
script:
    - py.test --cov=./
after_success:
  - codecov
